### ISSUE TITLE
Pid Limit

### ISSUE THREAD

**Issue by Farhanfdema** [kubernetes/enhancements#1827]
Is there a syntax to using pid limit in a kubernetes yaml file?

**Comment by palnabarun** [comment]
Hi @Farhanfdema :wave:, this repository is used to track Kubernetes Enhancements.

I think your question would be better answered in the `#kubernetes-users` channel on Kubernetes Slack (https://slack.k8s.io).

Thank you! :slightly_smiling_face: 

For now, I am closing this issue. Please feel free to reopen if you think otherwise.

/close
